CREATE TABLE USER(
                   USER_ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                   FIRST_NAME VARCHAR(50) NOT NULL,
                   LAST_NAME VARCHAR(50) NOT NULL,
                   ADDRESS VARCHAR(500),
                   LAST_MODIFIED TIMESTAMP,
                   VERSION INTEGER);

CREATE TABLE ACCOUNT(ACCOUNT_NUMBER BIGINT PRIMARY KEY AUTO_INCREMENT,
                       USER_ID BIGINT,
                       BALANCE DECIMAL(20,10),
                       CURRENCY VARCHAR(3),
                       ACCOUNT_TYPE INTEGER,
                       LAST_MODIFIED TIMESTAMP,
                       VERSION INTEGER
                       );

CREATE TABLE ACCOUNT_TYPES(ID INTEGER PRIMARY KEY,
                            TYPE VARCHAR(20) NOT NULL,
                            LAST_MODIFIED TIMESTAMP);


CREATE TABLE ACCOUNT_RECIPIENTS(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                               ACCOUNT_NUMBER BIGINT NOT NULL,
                               RECIPIENT_ACCOUNT BIGINT NOT NULL,
                                NAME VARCHAR(50),
                                CURRENCY VARCHAR(3),
                                VERSION INTEGER);

CREATE TABLE ACCOUNT_TRANSACTIONS(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                                SOURCE_ACCOUNT BIGINT NOT NULL,
                                DEST_ACCOUNT BIGINT NOT NULL,
                                AMOUNT DECIMAL(20,10) NOT NULL,
                                COMMENTS VARCHAR(100),
                                LAST_MODIFIED TIMESTAMP DEFAULT SYSTIMESTAMP,
                                VERSION INTEGER);

--ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_USER FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID);
ALTER TABLE ACCOUNT ADD CONSTRAINT FK_ACCOUNT_TYPE FOREIGN KEY(ACCOUNT_TYPE) REFERENCES ACCOUNT_TYPES(ID);
ALTER TABLE ACCOUNT_RECIPIENTS ADD CONSTRAINT FK_ACCOUNT_RECIPIENTS FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES ACCOUNT(ACCOUNT_NUMBER);

ALTER TABLE ACCOUNT_TRANSACTIONS ADD CONSTRAINT FK_ACCOUNT_TRANSACTIONS_SOURCE FOREIGN KEY(SOURCE_ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_NUMBER);
ALTER TABLE ACCOUNT_TRANSACTIONS ADD CONSTRAINT FK_ACCOUNT_TRANSACTIONS_DEST FOREIGN KEY(DEST_ACCOUNT) REFERENCES ACCOUNT(ACCOUNT_NUMBER);

INSERT INTO ACCOUNT_TYPES VALUES(1,'Checking',SYSTIMESTAMP);
INSERT INTO ACCOUNT_TYPES VALUES(2,'Savings',SYSTIMESTAMP);


INSERT INTO USER(
                   FIRST_NAME,
                   LAST_NAME,
                   ADDRESS,
                   LAST_MODIFIED,
                   VERSION) VALUES( 'John','King1','New York',SYSTIMESTAMP,0);

INSERT INTO USER(
                   FIRST_NAME,
                   LAST_NAME,
                   ADDRESS,
                   LAST_MODIFIED,
                   VERSION) VALUES( 'John','Snow','New Jersey',SYSTIMESTAMP,0);


INSERT INTO USER(
                   FIRST_NAME,
                   LAST_NAME,
                   ADDRESS,
                   LAST_MODIFIED,
                   VERSION) VALUES( 'Jaime','Lannister','Connecticut',SYSTIMESTAMP,0);


INSERT INTO ACCOUNT(USER_ID,BALANCE,CURRENCY,ACCOUNT_TYPE,LAST_MODIFIED,VERSION)
VALUES(
 (select USER_ID from user where first_name = 'John' and last_name = 'King1'),
 3000456,'USD',1,SYSTIMESTAMP,0);
 INSERT INTO ACCOUNT(USER_ID,BALANCE,CURRENCY,ACCOUNT_TYPE,LAST_MODIFIED,VERSION)
 VALUES(
  (select USER_ID from user where first_name = 'John' and last_name = 'King1'),
  3000456,'USD',2,SYSTIMESTAMP,0);

INSERT INTO ACCOUNT(USER_ID,BALANCE,CURRENCY,ACCOUNT_TYPE,LAST_MODIFIED,VERSION)
VALUES(
 (select USER_ID from user where first_name = 'John' and last_name = 'Snow'),
 3000456,'USD',1,SYSTIMESTAMP,0);
 INSERT INTO ACCOUNT(USER_ID,BALANCE,CURRENCY,ACCOUNT_TYPE,LAST_MODIFIED,VERSION)
 VALUES(
  (select USER_ID from user where first_name = 'Jaime' and last_name = 'Lannister'),
  3000456,'GBP',1,SYSTIMESTAMP,0);



INSERT INTO ACCOUNT_RECIPIENTS(ACCOUNT_NUMBER,RECIPIENT_ACCOUNT,NAME,CURRENCY,VERSION)
VALUES (
(SELECT ACCOUNT_NUMBER FROM ACCOUNT A JOIN USER B ON A.USER_ID = B.USER_ID WHERE B.FIRST_NAME = 'John' and b.LAST_NAME = 'Snow'),
(SELECT ACCOUNT_NUMBER FROM ACCOUNT A JOIN USER B ON A.USER_ID = B.USER_ID WHERE B.FIRST_NAME = 'Jaime' and b.LAST_NAME = 'Lannister'),
'JaimeLannister',
'GBP',
0
);

INSERT INTO ACCOUNT_RECIPIENTS(ACCOUNT_NUMBER,RECIPIENT_ACCOUNT,NAME,CURRENCY,VERSION)
VALUES (
(SELECT ACCOUNT_NUMBER FROM ACCOUNT A JOIN USER B ON A.USER_ID = B.USER_ID WHERE B.FIRST_NAME = 'John' and b.LAST_NAME = 'Snow'),
(SELECT ACCOUNT_NUMBER FROM ACCOUNT A JOIN USER B ON A.USER_ID = B.USER_ID WHERE B.FIRST_NAME = 'John' and b.LAST_NAME = 'King1' AND A.ACCOUNT_TYPE = 1),
'JohnKing1',
'USD',
0
);

commit;